-- Core schema, RLS helper functions, and the permission model.
-- Every object below is written idempotently, so that this migration can be re-run without error.

CREATE EXTENSION IF NOT EXISTS pgcrypto;
SET search_path = public, extensions;


-- ============================================================================
-- T Y P E S
-- ============================================================================

DO $$ BEGIN
  CREATE TYPE public.organization_role AS ENUM (
    'admin',
    'session_leader',
    'member'
  );
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE public.app_permission AS ENUM (
    'sessions.personal.start',
    'sessions.team.start',
    'sessions.team.join',
    'sessions.end.own',
    'sessions.end.any',
    'floor.raise_hand',
    'floor.grant',
    'board.post',
    'board.claim',
    'library.promote',
    'library.delete',
    'invites.manage',
    'join_code.regenerate',
    'members.role.change',
    'members.remove',
    'org.settings.manage',
    'billing.manage'
  );
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;


-- ============================================================================
-- T A B L E S
-- ============================================================================

CREATE TABLE IF NOT EXISTS organizations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  plan text NOT NULL DEFAULT 'free',
  join_code text UNIQUE NOT NULL DEFAULT substr(md5(random()::text), 1, 8),
  created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  stripe_customer_id text,
  stripe_subscription_id text,
  limit_overrides jsonb NOT NULL DEFAULT '{}',
  created_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE organizations IS 'One row per customer organization, including a Free-tier "org of one" created automatically at signup.';
COMMENT ON COLUMN organizations.join_code IS 'Regenerable code used to join as a Member. The previous code stops working the instant regenerate_join_code() runs.';
COMMENT ON COLUMN organizations.limit_overrides IS 'Superadmin per-org overrides of the plans defaults, keyed by the same limit column names as plans.';

CREATE TABLE IF NOT EXISTS memberships (
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  role organization_role NOT NULL DEFAULT 'member',
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, organization_id)
);

COMMENT ON TABLE memberships IS 'Join table: which user belongs to which organization, and in what role. Exactly one admin row must exist per organization at all times.';

CREATE TABLE IF NOT EXISTS platform_admins (
  user_id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE
);

COMMENT ON TABLE platform_admins IS 'Superadmins: platform operators who are not members of any customer organization. A row''s existence is what is_platform_admin() checks.';

CREATE TABLE IF NOT EXISTS role_permissions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role organization_role NOT NULL,
  permission app_permission NOT NULL,
  UNIQUE (role, permission)
);

COMMENT ON TABLE role_permissions IS 'Static role -> permission mapping. Read-only at runtime — changed only by a future migration or a Superadmin override.';

CREATE TABLE IF NOT EXISTS plans (
  tier text PRIMARY KEY,
  price_cents integer NOT NULL DEFAULT 0,
  max_members integer,
  max_minutes_per_session integer,
  team_session_limit integer,
  solo_session_limit_per_member integer,
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by uuid REFERENCES auth.users(id)
);

COMMENT ON TABLE plans IS 'Canonical, Superadmin-editable tier definitions. organizations.plan looks up its default limits here; organizations.limit_overrides supersedes these per-org, per-field, when set.';

CREATE TABLE IF NOT EXISTS organization_invites (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  email text NOT NULL,
  role organization_role NOT NULL DEFAULT 'member' CHECK (role <> 'admin'),
  invited_by uuid NOT NULL REFERENCES auth.users(id),
  token text UNIQUE NOT NULL DEFAULT encode(gen_random_bytes(24), 'hex'),
  status text NOT NULL DEFAULT 'pending',
  created_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamptz NOT NULL DEFAULT (now() + INTERVAL '7 days')
);

COMMENT ON TABLE organization_invites IS 'Pending email invitations. role can never be admin — the only way to become Admin is the handoff, never an invite.';


-- ============================================================================
-- R L S:  H E L P E R  F U N C T I O N S
-- ============================================================================

CREATE OR REPLACE FUNCTION is_platform_admin() RETURNS boolean
LANGUAGE sql
SECURITY DEFINER
STABLE
SET search_path = public
AS $$
  SELECT EXISTS (SELECT 1 FROM platform_admins WHERE user_id = auth.uid());
$$;

COMMENT ON FUNCTION is_platform_admin() IS 'True if the current user is a Superadmin — a row exists for them in platform_admins.';

CREATE OR REPLACE FUNCTION is_organization_member(check_organization_id uuid) RETURNS boolean
LANGUAGE sql
SECURITY DEFINER
STABLE
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1 FROM memberships
    WHERE organization_id = check_organization_id
      AND user_id = auth.uid()
  );
$$;

COMMENT ON FUNCTION is_organization_member(uuid) IS 'True if the current user belongs to the given organization, in any role.';

CREATE OR REPLACE FUNCTION has_role(check_organization_id uuid, exact_role organization_role) RETURNS boolean
LANGUAGE sql
SECURITY DEFINER
STABLE
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1 FROM memberships
    WHERE organization_id = check_organization_id
      AND user_id = auth.uid()
      AND role = exact_role
  );
$$;

COMMENT ON FUNCTION has_role(uuid, organization_role) IS 'True if the current user holds exactly the given role in the given organization. Reserved for role-identity checks — feature gating use has_permission().';

CREATE OR REPLACE FUNCTION has_permission(check_organization_id uuid, permission app_permission) RETURNS boolean
LANGUAGE sql
SECURITY DEFINER
STABLE
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1
      FROM memberships m
      JOIN role_permissions rp ON rp.role = m.role
      WHERE m.organization_id = check_organization_id
        AND m.user_id = auth.uid()
        -- Qualified as has_permission.permission (not a bare `permission`) because
        -- the parameter name collides with the rp.permission column in this query.
        -- PostgreSQL resolves an unqualified name to the column when both are in
        -- scope, so a bare `permission` here would silently compare rp.permission
        -- to itself and always return true — this qualification is what makes the
        -- check actually compare against the caller's requested permission.
        AND rp.permission = has_permission.permission
  );
$$;

COMMENT ON FUNCTION has_permission(uuid, app_permission) IS 'True if the current user''s role in the given organization is seeded, via role_permissions, with the given permission. The primary authorization check for RLS policies and RPCs.';


-- ============================================================================
-- R L S:  S U P E R A D M I N
-- ============================================================================

ALTER TABLE plans ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anyone can read plans" ON plans;
CREATE POLICY "anyone can read plans" ON plans
  FOR SELECT
  USING (TRUE);

DROP POLICY IF EXISTS "only superadmin edits plans" ON plans;
CREATE POLICY "only superadmin edits plans" ON plans
  FOR ALL
  TO authenticated
  USING (is_platform_admin())
  WITH CHECK (is_platform_admin());

ALTER TABLE platform_admins ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "a superadmin user can check their own platform-admin status" ON platform_admins;
CREATE POLICY "a superadmin user can check their own platform-admin status" ON platform_admins
  FOR SELECT
  USING (user_id = auth.uid());


-- ============================================================================
-- R L S:  R O L E _ P E R M I S S I O N S
-- ============================================================================

ALTER TABLE role_permissions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anyone can read role_permissions" ON role_permissions;
CREATE POLICY "anyone can read role_permissions" ON role_permissions
  FOR SELECT
  USING (TRUE);


-- ============================================================================
-- R L S:  O R G A N I Z A T I O N S  A N D  M E M B E R S H I P S
-- ============================================================================

ALTER TABLE organizations ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "members can view their own organization" ON organizations;
CREATE POLICY "members can view their own organization" ON organizations
  FOR SELECT
  TO authenticated
  USING (is_organization_member(id));

ALTER TABLE memberships ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "members can view memberships in their own organization" ON memberships;
CREATE POLICY "members can view memberships in their own organization" ON memberships
  FOR SELECT
  TO authenticated
  USING (is_organization_member(organization_id));

ALTER TABLE organization_invites ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "admins manage invites for their organizations" ON organization_invites;
CREATE POLICY "admins manage invites for their organizations" ON organization_invites
  FOR ALL
  TO authenticated
  USING (has_permission(organization_id, 'invites.manage')
    OR is_platform_admin());


-- ============================================================================
-- T R I G G E R S
-- ============================================================================

CREATE OR REPLACE FUNCTION prevent_admin_membership_delete() RETURNS trigger
LANGUAGE plpgsql
SET search_path = public
AS $$
  BEGIN
    IF old.role = 'admin' AND EXISTS (
      SELECT 1 FROM memberships
      WHERE organization_id = old.organization_id
        AND user_id <> old.user_id
    ) THEN
      RAISE EXCEPTION 'Cannot delete an organization''s Admin membership directly while other members exist. Hand off the Admin role first';
    END IF;
    RETURN old;
  END;
$$;

COMMENT ON FUNCTION prevent_admin_membership_delete() IS 'Defense-in-depth: blocks direct deletion of an admin-role membership row while other members remain in the org and the handoff is the only sanctioned way to change admins in that case. Allowed when the admin is the org''s only member like deleting a solo Free account.';

DROP TRIGGER IF EXISTS memberships_prevent_admin_delete ON memberships;
CREATE TRIGGER memberships_prevent_admin_delete
  BEFORE DELETE ON memberships
  FOR EACH ROW EXECUTE FUNCTION prevent_admin_membership_delete();

CREATE OR REPLACE FUNCTION restrict_memberships_update_columns() RETURNS trigger
LANGUAGE plpgsql
AS $$
  BEGIN
    IF new.user_id <> old.user_id OR new.organization_id <> old.organization_id THEN
      RAISE EXCEPTION 'Only the role column of a membership row may be updated';
    END IF;
    RETURN new;
  END;
$$;

COMMENT ON FUNCTION restrict_memberships_update_columns() IS 'Defense-in-depth: a membership row''s user_id and organization_id may never change after creation — only role may.';

DROP TRIGGER IF EXISTS memberships_restrict_update ON memberships;
CREATE TRIGGER memberships_restrict_update
  BEFORE UPDATE ON memberships
  FOR EACH ROW EXECUTE FUNCTION restrict_memberships_update_columns();


-- ============================================================================
-- I N S E R T
-- ============================================================================

INSERT INTO plans (
  tier,
  price_cents,
  max_minutes_per_session,
  team_session_limit,
  solo_session_limit_per_member,
  max_members)
VALUES
  ('free', 0, 60, 0, 3, 1),
  ('basic', 15, 120, 10, 5, 30),
  ('pro', 30, 120, 50, 10, 100),
  ('ultra', 50, 300, 100, 20, 100)
ON CONFLICT (tier) DO NOTHING;

INSERT INTO role_permissions (role, permission) VALUES
  ('admin', 'sessions.personal.start'),
  ('admin', 'sessions.team.start'),
  ('admin', 'sessions.team.join'),
  ('admin', 'floor.raise_hand'),
  ('admin', 'floor.grant'),
  ('admin', 'sessions.end.own'),
  ('admin', 'sessions.end.any'),
  ('admin', 'board.claim'),
  ('admin', 'library.promote'),
  ('admin', 'library.delete'),
  ('admin', 'invites.manage'),
  ('admin', 'join_code.regenerate'),
  ('admin', 'members.role.change'),
  ('admin', 'members.remove'),
  ('admin', 'org.settings.manage'),
  ('admin', 'billing.manage'),
  ('session_leader', 'sessions.personal.start'),
  ('session_leader', 'sessions.team.start'),
  ('session_leader', 'sessions.team.join'),
  ('session_leader', 'floor.raise_hand'),
  ('session_leader', 'floor.grant'),
  ('session_leader', 'sessions.end.own'),
  ('session_leader', 'board.claim'),
  ('session_leader', 'library.promote'),
  ('member', 'sessions.personal.start'),
  ('member', 'sessions.team.join'),
  ('member', 'floor.raise_hand'),
  ('member', 'board.post'),
  ('member', 'library.promote')
ON CONFLICT (role, permission) DO NOTHING;
